
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lilcoin_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  address:
    62.164.220.205
  port: 8080

logging:
  level:
    org:
    springframework:
      web:
        socket: DEBUG
      messaging:
        simp: DEBUG

bot:
  name: Lilcoin1_bot
  token: 7113595834:AAEl2QvrT1kv-fJrQaTqcZ9vIqKaOYN7paY