spring:
  profiles:
    active: prod

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 315576000000 # 10 years
      refresh-token:
        expiration: 315576000000 # 10 years

logging:
  level:
    org:
    springframework:
      web:
        socket: DEBUG
      messaging:
        simp: DEBUG

bot:
  name: Lilcoin1_bot
  token: 7113595834:AAEl2QvrT1kv-fJrQaTqcZ9vIqKaOYN7paY
